name: Build APK with Kivy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential zip unzip openjdk-17-jdk libffi-dev libssl-dev libncurses5
        pip install --upgrade pip
        pip install buildozer cython

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      - uses: actions/upload-artifact@v4

      with:
        name: kivy-apk
        path: bin/*.apk
